### ISSUE TITLE
Error when pip installing

### ISSUE THREAD

**Issue by lcaldwell** [gsmke/django-quill#6]
I can't seem to install this using pip. It complains about not being able to find the DESCRIPTION.rst file. Is this happening for anyone else?

```
Collecting django-quill
  Using cached django-quill-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/44/97sht4l92c5560jwvlsnm0c80000gn/T/pip-build-A2WfHB/django-quill/setup.py", line 9, in <module>
        with open(os.path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "/Users/lukecaldwell/Documents/Repos/web/project/venv/lib/python2.7/codecs.py", line 884, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/44/97sht4l92c5560jwvlsnm0c80000gn/T/pip-build-A2WfHB/django-quill/DESCRIPTION.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/44/97sht4l92c5560jwvlsnm0c80000gn/T/pip-build-A2WfHB/django-quill/
```

**Comment by chris-erickson** [comment]
Not seeing the problem here.  Just used it on a Django 1.8 project.  Was pypi just down when you tried this?

**Comment by JonhatanHaisi** [comment]
I have the same error.
I'm using Django 1.10.3

`(python_sample) D:\wiki\python_sample>pip install django-quill
Collecting django-quill
  Using cached django-quill-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jhaisi\appdata\local\temp\pip-build-fgggqr\django-quill\setup.py", line 9, in <module>
        with open(os.path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "d:\wiki\python_sample\lib\codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'c:\\users\\jhaisi\\appdata\\local\\temp\\pip-build-fgggqr\\django-quill\\DESCRIPTION.rst'`

**Comment by JonhatanHaisi** [comment]
I have the same error.
I'm using Django 1.10.3

`````` <code>
Collecting django-quill
 Using cached django-quill-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jhaisi\appdata\local\temp\pip-build-fgggqr\django-quill\setup.py", line 9, in <module>
        with open(os.path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "d:\wiki\python_sample\lib\codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'c:\\users\\jhaisi\\appdata\\local\\temp\\pip-build-fgggqr\\django-quill\\DESCRIPTION.rst'
</code>```
``````

**Comment by chris-erickson** [comment]
I don't have any ideas.  We use this on a regular basis without issue, sorry.

**Comment by agscala** [comment]
I also have this issue on OSX using virtualenv.

```
agscala$ pip install django-quill
Collecting django-quill
  Using cached django-quill-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lp/v5fd7byd68v7l6n9lpn5xdm00000gn/T/pip-build-ttkma6/django-quill/setup.py", line 9, in <module>
        with open(os.path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "/Users/agscala/workspace/hundredanhour/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/lp/v5fd7byd68v7l6n9lpn5xdm00000gn/T/pip-build-ttkma6/django-quill/DESCRIPTION.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/lp/v5fd7byd68v7l6n9lpn5xdm00000gn/T/pip-build-ttkma6/django-quill/
```

edit: It looks like an issue with python2.7. Using pip3 installs django-pip successfully.

**Comment by chris-erickson** [comment]
I've seen issues with some of the version 8 series (and maybe older) of `pip` that are gone in 9.  I don't know if this is related or not.
